Repository blutui/blutui-node, pull requests merged in 2024-05, with the labels that each got.

#11 feat: Add the ability to use the agency API
  .gitignore
  jest.config.ts
  src/agency.ts
  src/blutui.spec.ts
  src/blutui.ts
  src/exceptions/index.ts
  src/exceptions/not-found.exception.ts
  src/resources/agency/brand/brand.spec.ts
  src/resources/agency/brand/brand.ts
  src/resources/agency/brand/fixtures/brand.json
  src/resources/agency/brand/interfaces/brand.interface.ts
  src/resources/agency/brand/interfaces/create-brand-options.interface.ts
  src/resources/agency/brand/interfaces/index.ts
  src/resources/agency/brand/interfaces/update-brand-options.interface.ts
  src/resources/agency/brand/serializers/brand.serializer.ts
  src/resources/agency/brand/serializers/create-brand-options.serializer.ts
  src/resources/agency/brand/serializers/index.ts
  src/resources/agency/brand/serializers/update-brand-options.serializer.ts
  src/resources/agency/domains/domains.ts
  src/resources/agency/index.ts
  src/resources/site/index.ts
  src/resources/user/user.spec.ts
  src/resources/user/user.ts
  src/types.ts
  src/utils/client.spec.ts
  src/utils/client.ts
  tsconfig.json
Labels: enhancement

#17 feat: Handle API errors
  src/agency.ts
  src/blutui.ts
  src/exceptions/authorization.exception.ts
  src/exceptions/index.ts
  src/exceptions/validation.exception.ts
  src/resources/agency/brand/brand.spec.ts
  src/resources/agency/brand/brand.ts
  src/resources/agency/domains/domains.ts
  src/resources/agency/index.ts
  src/resources/user/user.ts
  src/types.ts
  src/utils/client.ts
Labels: bug, enhancement

#19 fix: make agencies variable private
  src/blutui.ts
Labels: good first issue
